baseURL = "https://rashisahu.netlify.app/"
languageCode = "en-US"
title = "Rashi Sahu"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-192420891-1"
theme = "hugo-sustain"
highlight = true

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "img/profile.png"
  author = "Rashi Sahu"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "rashi-sahu"
  Email         = "rashisahu43@gmail.com"
  Twitter       = "RashiSahu11"
  LinkedIn      = "rashi-sahu-571708127"

## Main Menu
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 100
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 200
  url = "/resume.pdf/"
[[menu.main]]
  name = "Tech Stack"
  weight = 300
  identifier = "stack"
  url = "/stack/"
